### PR TITLE
Add config variable config.py.example

### PR DESCRIPTION
**Pull request by nsandler1**

### CODE REVIEW

**Comment by tybug** [comment]
where is this being used?

**Comment by nsandler1** [comment]
It will be used in settings.py for [this](https://docs.djangoproject.com/en/4.1/ref/settings/#admins) purpose.

**Comment by tybug** [comment]
but where is this being used in this PR? I don't see any usage

**Comment by nsandler1** [comment]
now you do :)

**Review by tybug — APPROVED** [review]

**Pull request merged**
