### PR TITLE
forget your password aligned to right

### PR DESCRIPTION
**Pull request by tymnec**
Issue #127

### CODE REVIEW

**Comment by tybug** [comment]
this has the "forgot password" text too far right:

image


It should be aligned right to the end of the "password" text box. It should also not cause any extra vertical space to appear above the "login" button.

**Comment by tymnec** [comment]
ok I will do that

**Comment by tymnec** [comment]
image

**Comment by tymnec** [comment]
After removing the bottom padding of forget your password?
image

**Comment by tybug** [comment]
There's still vertical space above the login button. You'll likely need to put the login button and the forgot password element into the same parent div in order to get them to have the same vertical spacing.

**Comment by tymnec** [comment]
check it now: 
image

**Comment by tybug** [comment]
Thanks for the contribution @tymnec, and sorry to have left this hanging. https://github.com/planetterp/PlanetTerp/pull/149 addressed this in a slightly better (but similar) way, so I'm going to close this.

**Pull request closed without merging**
